export const mockImageInformation = {
  alt_description: 'Beautiful photography',
  alternative_slugs: {},
  asset_type: 'photo',
  blur_hash: 'LGG+ae4n4UWCNHIU?bxu00IUxu%M',
  breadcrumbs: [],
  color: '#8B9DC3',
  created_at: new Date().toISOString(),
  current_user_collections: [],
  description: 'A stunning photograph captured with artistic vision',
  downloads: 15000,
  exif: {
    aperture: null,
    exposure_time: null,
    focal_length: null,
    iso: null,
    make: null,
    model: null,
    name: null,
  },
  height: 2000,
  id: 'mock-image-id',
  liked_by_user: false,
  likes: 850,
  links: {
    download: 'https://unsplash.com/photos/mock-image/download',
    download_location: 'https://api.unsplash.com/photos/mock-image/download',
    html: 'https://unsplash.com/photos/mock-image',
    self: 'https://api.unsplash.com/photos/mock-image',
  },
  location: {
    city: null,
    country: null,
    name: null,
    position: {
      latitude: null,
      longitude: null,
    },
  },
  meta: {
    index: true,
  },
  promoted_at: new Date().toISOString(),
  public_domain: false,
  related_collections: {
    results: [],
    total: 0,
    type: 'related',
  },
  slug: 'mock-image',
  sponsorship: null,
  tags: [
    { title: 'photography', type: 'search' },
    { title: 'art', type: 'search' },
    { title: 'nature', type: 'search' },
    { title: 'beautiful', type: 'search' },
    { title: 'creative', type: 'search' },
    { title: 'inspiration', type: 'search' },
  ],
  topic_submissions: {},
  topics: [],
  updated_at: new Date().toISOString(),
  urls: {
    full: 'https://images.unsplash.com/photo-mock',
    raw: 'https://images.unsplash.com/photo-mock',
    regular: 'https://images.unsplash.com/photo-mock',
    small: 'https://images.unsplash.com/photo-mock',
    small_s3: 'https://images.unsplash.com/photo-mock',
    thumb: 'https://images.unsplash.com/photo-mock',
  },
  user: {
    accepted_tos: true,
    bio: 'Passionate photographer sharing moments of beauty',
    first_name: 'Photographer',
    for_hire: false,
    id: 'mock-user-id',
    instagram_username: 'photographer',
    last_name: 'Artist',
    links: {
      followers: 'https://api.unsplash.com/users/photographer/followers',
      following: 'https://api.unsplash.com/users/photographer/following',
      html: 'https://unsplash.com/@photographer',
      likes: 'https://api.unsplash.com/users/photographer/likes',
      photos: 'https://api.unsplash.com/users/photographer/photos',
      portfolio: 'https://unsplash.com/users/photographer/portfolio',
      self: 'https://api.unsplash.com/users/photographer',
    },
    location: 'World',
    name: 'Photographer Artist',
    portfolio_url: null,
    profile_image: {
      large: 'https://images.unsplash.com/profile-mock-large',
      medium: 'https://images.unsplash.com/profile-mock-medium',
      small: 'https://images.unsplash.com/profile-mock-small',
    },
    social: {
      instagram_username: 'photographer',
      paypal_email: null,
      portfolio_url: null,
      twitter_username: null,
    },
    total_collections: 5,
    total_illustrations: 0,
    total_likes: 1200,
    total_photos: 50,
    total_promoted_illustrations: 0,
    total_promoted_photos: 10,
    twitter_username: null,
    updated_at: new Date().toISOString(),
    username: 'photographer',
  },
  views: 25000,
  width: 3000,
}; 